from typing import Dict

base_id = 345600000

attack_magics: Dict[str, int] = {
    "Arcane": base_id,
    "Ice": base_id + 1,
    "Fire": base_id + 2,
    "Thunder": base_id + 3,
}

useful_items: Dict[str, int] = {
    "Wind": base_id + 4,
    "Mana Absorption": base_id + 5,
    "Progressive Bag Upgrade": base_id + 6,
    "Teleport": base_id + 23,
}

boss_souls: Dict[str, int] = {
    "Specter Armor Soul": base_id + 7,
    "Tania Soul": base_id + 8,
    "Monica Soul": base_id + 9,
    "Enraged Armor Soul": base_id + 10,
    "Vanessa Soul": base_id + 11,
    "Queen Vanessa V2 Soul": base_id + 12,
}

filler_items: Dict[str, int] = {
    "HPCure": base_id + 13,
    "HPCureMiddle": base_id + 14,
    "HPCureBig": base_id + 15,
    "MPCure": base_id + 16,
    "MPCureMiddle": base_id + 17,
    "MPCureBig": base_id + 18,
    "Defense": base_id + 19,
    "DefenseMiddle": base_id + 20,
    "DefenseBig": base_id + 21,
    "Souls": base_id + 22,
}

lore_items: Dict[str, int] = {
    "1. Crafted Soul Reader": base_id + 25,
    "2. Stained Ribbon": base_id + 26,
    "3. Copper Coin": base_id + 27,
    "4. Unknown House Banner": base_id + 28,
    "5. Melted Silver Candlestick": base_id + 29,
    "6. Broken Cross Spear": base_id + 30,
    "7. Deformed Cavalier Armor": base_id + 31,
    "8. Hero's Cross Sword": base_id + 32,
    "9. Giant Axe": base_id + 33,
    "10. Shield of the Church": base_id + 34,
    "11. Broken Queen Doll": base_id + 35,
    "12. Pointy Witch's Hat": base_id + 36,
    "13. Sleeve Dagger": base_id + 37,
    "14. Corpse Shroud": base_id + 38,
    "15. Headcutter Circular Saw": base_id + 39,
    "16. Test Subject Manacle": base_id + 40,
    "17. Tattered Maid Outfit": base_id + 41,
    "18. Soul Doll Remnant": base_id + 42,
    "19. Knight's Halberd": base_id + 43,
    "20. Weathered Cloak": base_id + 44,
    "21. Silver Coin": base_id + 45,
    "22. Intricate Clock": base_id + 46,
    "24. Cursed Turquoise Necklace": base_id + 47,
    "24. Glass Lantern": base_id + 48,
    "25. Copper Ingot": base_id + 49,
    "26. Teddy Bear": base_id + 50,
    "27. Fractured Stone Axe": base_id + 51,
    "28. Cage": base_id + 52,
    "29. Slave Branding Iron": base_id + 53,
    "30. Merchant's Ledger": base_id + 54,
    "31. Slave Tag": base_id + 55,
    "32. Slave Collar": base_id + 56,
    "33. Bestian Palm": base_id + 57,
    "34. Bestian Ear": base_id + 58,
    "35. Dwarven Metalwork": base_id + 59,
    "36. High Elf's Mana Ring": base_id + 60,
    "37. Forest Elf's Vest": base_id + 61,
    "38. Dark Elf's Ear Sample": base_id + 62,
    "39. Dark Elf's Short Bow": base_id + 63,
    "40. Ogre's Kidney": base_id + 64,
    "41. Ogre's Eye": base_id + 65,
    "42. Ogre's Club": base_id + 66,
    "43. Bloodstained Javelin": base_id + 67,
    "44. Nomad's Cookware": base_id + 68,
    "45. Golden Coin": base_id + 69,
    "46. Tooth Thief's Pouch": base_id + 70,
    "47. Blood Orc's Skin Sample": base_id + 71,
    "48. Chief's Skull": base_id + 72,
    "49. Chief's Skull": base_id + 73,
    "50. Crafted Soul Injector": base_id + 74,
    "51. Hero's Insignia": base_id + 75,
    "52. Mutated Beast Claw": base_id + 76,
    "53. Ceremonial Sword": base_id + 77,
    "54. Banner of the Lance Hero": base_id + 78,
    "55. Banner of the Lionhearted": base_id + 79,
    "56. Knight Kingdom Crown": base_id + 80,
    "57. Lady's Feather Hat": base_id + 81,
    "58. Super Cleanser Soap": base_id + 82,
    "59. Exquisite Leather Lamp": base_id + 83,
    "60. Premium Grass Ash": base_id + 84,
    "61. Knight Kingdom Entry Pass": base_id + 85,
    "62. Bone Chess Set": base_id + 86,
    "63. Inquisitor's List": base_id + 87,
    "64. Envoy's Rune": base_id + 88,
    "65. Declaration of War": base_id + 89,
    "66. Attic Key": base_id + 90,
    "67. Halfling's Forelimb": base_id + 91,
    "68. Ratian Claw": base_id + 92,
    "69. Pontiff's Scepter": base_id + 93,
    "70. Abandoned Rag Doll": base_id + 94,
    "71. Apocalypse Knight Record": base_id + 95,
    "72. Apocalypse Knight Shield": base_id + 96,
    "73. Apocalypse Knight Axe": base_id + 97,
    "74. Apocalypse Knight Staff": base_id + 98,
    "75. Apocalypse Knight Bow": base_id + 99,
    "76. Apocalypse Knight Sword": base_id + 100,
    "77. The Throne": base_id + 101,
    "78. Ancient Throne Rune": base_id + 102,
    "79. Doctor's Mask": base_id + 103,
    "80. Ceremonial Incense": base_id + 104,
    "81. Moonlight Blade": base_id + 105,
    "82. Prostitute's Chiffon": base_id + 106,
    "83. Castle Blueprint": base_id + 107,
    "84. Witch Worshipper Puppet": base_id + 108,
    "85. Polymorphism Scroll": base_id + 109,
    "86. Missing Person Poster": base_id + 110,
    "87. Saint's Cane": base_id + 111,
    "88. Hero Summon Rune": base_id + 112,
    "89. Bloodstained Key": base_id + 113,
    "90. Enchanted Shackles": base_id + 114,
    "91. Gaseous Soul Essence": base_id + 115,
    "92. Semi-gaseous Soul Essence": base_id + 116,
    "93. Enchanted Soul Shard": base_id + 117,
    "94. Knight's Soul Shard": base_id + 118,
    "95. Refined Soul Shard": base_id + 119,
    "96. Knight's Soul Shard": base_id + 120,
    "97. Faithful Soul Shard": base_id + 121,
    "98. Lost Maiden's Soul Shard": base_id + 122,
    "99. Child's Soul Shard": base_id + 123,
    "100. King's Final Honor": base_id + 124,
    "101. Proud King's Crafted Soul Shard": base_id + 125,
    "102. Lost Maiden's Crafted Soul Shard": base_id + 126,
    "103. Loyal Soul Shard": base_id + 127
}

lwn_items: Dict[str, int] = {
    **attack_magics,
    **useful_items,
    **boss_souls,
    **filler_items,
    "Trial Key": base_id + 24,
    **lore_items
}

item_name_groups = {
    "Attack Magics": attack_magics,
    "Boss Souls": boss_souls,
    "Double Jump": "Wind",
    "Counter": "Mana Absorption",
    "Lore": lore_items,
    "Magic Barrier": barrier_items,
    "Metal Gate": gate_items
}

lookup_id_to_name: Dict[int, str] = {id: name for name, id in lwn_items.items()}
