from typing import Dict, Set, Any

base_id = 345600000

attack_magics: Set[str] = {
    "Arcane",
    "Ice",
    "Fire",
    "Thunder",
}

useful_items: Set[str] = {
    "Wind",
    "Mana Absorption",
    "Progressive Bag Upgrade",
}

boss_souls: Set[str] = {
    "Specter Armor Soul",
    "Tania Soul",
    "Monica Soul",
    "Enraged Armor Soul",
    "Vanessa Soul",
    "Queen Vanessa V2 Soul",
}

filler_items: Set[str] = {
    "HPCure",
    "HPCureMiddle",
    "HPCureBig",
    "MPCure",
    "MPCureMiddle",
    "MPCureBig",
    "Defense",
    "DefenseMiddle",
    "DefenseBig",
    "Souls",
}

lore_items: set[str] = {
    "1. Crafted Soul Reader",
    "2. Stained Ribbon",
    "3. Copper Coin",
    "4. Unknown House Banner",
    "5. Melted Silver Candlestick",
    "6. Broken Cross Spear",
    "7. Deformed Cavalier Armor",
    "8. Hero's Cross Sword",
    "9. Giant Axe",
    "10. Shield of the Church",
    "11. Broken Queen Doll",
    "12. Pointy Witch's Hat",
    "13. Sleeve Dagger",
    "14. Corpse Shroud",
    "15. Headcutter Circular Saw",
    "16. Test Subject Manacle",
    "17. Tattered Maid Outfit",
    "18. Soul Doll Remnant",
    "19. Knight's Halberd",
    "20. Weathered Cloak",
    "21. Silver Coin",
    "22. Intricate Clock",
    "24. Cursed Turquoise Necklace",
    "24. Glass Lantern",
    "25. Copper Ingot",
    "26. Teddy Bear",
    "27. Fractured Stone Axe",
    "28. Cage",
    "29. Slave Branding Iron",
    "30. Merchant's Ledger",
    "31. Slave Tag",
    "32. Slave Collar",
    "33. Bestian Palm",
    "34. Bestian Ear",
    "35. Dwarven Metalwork",
    "36. High Elf's Mana Ring",
    "37. Forest Elf's Vest",
    "38. Dark Elf's Ear Sample",
    "39. Dark Elf's Short Bow",
    "40. Ogre's Kidney",
    "41. Ogre's Eye",
    "42. Ogre's Club",
    "43. Bloodstained Javelin",
    "44. Nomad's Cookware",
    "45. Golden Coin",
    "46. Tooth Thief's Pouch",
    "47. Blood Orc's Skin Sample",
    "48. Chief's Skull",
    "49. Chief's Skull",
    "50. Crafted Soul Injector",
    "51. Hero's Insignia",
    "52. Mutated Beast Claw",
    "53. Ceremonial Sword",
    "54. Banner of the Lance Hero",
    "55. Banner of the Lionhearted",
    "56. Knight Kingdom Crown",
    "57. Lady's Feather Hat",
    "58. Super Cleanser Soap",
    "59. Exquisite Leather Lamp",
    "60. Premium Grass Ash",
    "61. Knight Kingdom Entry Pass",
    "62. Bone Chess Set",
    "63. Inquisitor's List",
    "64. Envoy's Rune",
    "65. Declaration of War",
    "66. Attic Key",
    "67. Halfling's Forelimb",
    "68. Ratian Claw",
    "69. Pontiff's Scepter",
    "70. Abandoned Rag Doll",
    "71. Apocalypse Knight Record",
    "72. Apocalypse Knight Shield",
    "73. Apocalypse Knight Axe",
    "74. Apocalypse Knight Staff",
    "75. Apocalypse Knight Bow",
    "76. Apocalypse Knight Sword",
    "77. The Throne",
    "78. Ancient Throne Rune",
    "79. Doctor's Mask",
    "80. Ceremonial Incense",
    "81. Moonlight Blade",
    "82. Prostitute's Chiffon",
    "83. Castle Blueprint",
    "84. Witch Worshipper Puppet",
    "85. Polymorphism Scroll",
    "86. Missing Person Poster",
    "87. Saint's Cane",
    "88. Hero Summon Rune",
    "89. Bloodstained Key",
    "90. Enchanted Shackles",
    "91. Gaseous Soul Essence",
    "92. Semi-gaseous Soul Essence",
    "93. Enchanted Soul Shard",
    "94. Knight's Soul Shard",
    "95. Refined Soul Shard",
    "96. Knight's Soul Shard",
    "97. Faithful Soul Shard",
    "98. Lost Maiden's Soul Shard",
    "99. Child's Soul Shard",
    "100. King's Final Honor",
    "101. Proud King's Crafted Soul Shard",
    "102. Lost Maiden's Crafted Soul Shard",
    "103. Loyal Soul Shard"
}

barrier_items: Set[str] = {
    "Shrine First Magic Barrier",
    "Shrine Second Magic Barrier",
    "Secret Passage Entrance Magic Barrier",
    "Secret Passage First Fire Barrier",
    "Secret Passage Second Fire Barrier",
    "Shrine Secret Area Shortcut Gate",
    "Defeat Enraged Armor Barrier",
    "Underground Magic Barrier At Maid Enemy",
    "Underground Fire Barrier Magic Barrier",
    "Underground Enemy Magic Barrier",
    "Lava Ruins Magic Platforms",
    "Lava Ruins Scissor Enemy Barrier",
    "Lava Ruins Scissor Enemy Lift",
    "Lava Ruins Fire Magic Barrier",
    "Dark Tunnel First Magic Barrier",
    "Dark Tunnel Light Switch Barrier",
    "Dark Tunnel Thunder Barrier",
    "Dark Tunnel Floating Platform One",
    "Dark Tunnel Floating Platform Two",
    "Dark Tunnel Floating Platform Three",
    "Spirit Realm Arcane Barrier",
    "Spirit Realm First Seal Magic Barrier",
    "Spirit Realm Second Seal Magic Barrier",
    "Spirit Realm Elevator",
    "Spirit Realm Teleporter",
    "Abyss After Giant Maid Barrier",
    "Abyss Underground Trial Magic Switch",
    "Abyss After Scissor Enemy Barrier",
    "Abyss Lava Ruins Trial Magic Switch",
    "Abyss Dark Tunnel Trial Magic Switch",
    "Abyss Dark Tunnel Trial Maid Enemy Barrier",
    "Abyss Lava Ruins Trial Maid Enemy Barrier",
    "Spirit Realm Fire Deactivation",
    "Spirit Realm Magic Switch Barrier",
}

gate_items: Set[str] = {
    "Shrine Secret Boss Shortcut Gate",
    "Shrine Underground Shortcut Gate",
    "Secret Passage Dark Tunnel Shortcut Gate",
    "Underground Lava Ruins Shortcut Gate",
    "Underground Tania Shortcut Gate On Grand Hall Side",
    "Underground Tania Shortcut Gate On Tania Side",
    "Lava Ruins Monica Warp Gate",
    "Dark Tunnel First Gate",
    "Spirit Realm Statue Shortcut Gate",
    "Abyss First Gate",
    "Abyss Left Trap Gate",
    "Spirit Realm - Wind Spell Chest Gate",
    "Lava Ruins Fake Floor Shortcut Gate",
    "Spirit Realm - Ice spell Chest Gate",
    "Lava Ruins Monica Shortcut Gate",
}

lwn_items: Dict[str, Any] = {
    **dict.fromkeys(attack_magics, None),
    **dict.fromkeys(useful_items, None),
    **dict.fromkeys(boss_souls, None),
    **dict.fromkeys(filler_items, None),
    **dict.fromkeys(lore_items, None),
    **dict.fromkeys(barrier_items, None),
    **dict.fromkeys(gate_items, None),
    "Teleport": None,
    "Trial Key": None,
}

item_name_groups = {
    "Attack Magics": attack_magics,
    "Boss Souls": boss_souls,
    "Double Jump": "Wind",
    "Counter": "Mana Absorption",
    "Lore": lore_items,
    "Magic Barrier": barrier_items,
    "Metal Gate": gate_items
}

item_name_to_id: Dict[str, int] = {name: base_id + index for index, name in enumerate(lwn_items)}
